runtime: python311
service: backend
instance_class: F2  

# Full application entrypoint
entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 1

automatic_scaling:
  min_instances: 1
  max_instances: 2
  min_idle_instances: 1
  max_idle_instances: 1

env_variables:
  MONGO_URI: "mongodb+srv://Astrocare7:Astrocare7337@cluster0.ydviwil.mongodb.net/"
  DB_NAME: "Astrocare7"
  GEMINI_API_KEY: "AIzaSyBuu5Pw3aq38MIuTA24qu4M1sPhDfdMEc0"
  SECRET_KEY: "9bc5f5ce2dc60b380533703ed545b71a40b807d5269a41358eb0e6a6ebe2342e"
  GOOGLE_CLIENT_ID: "209987574410-rpfj1o45f6igoem4fnjiefmhjmbjohf3.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_REDIRECT_URI: "https://ai-astrology-481805.as.r.appspot.com/api/v1/auth/google/callback"
  FACEBOOK_APP_ID: "4171301276441086"
  FACEBOOK_APP_SECRET: "dda90c714ffa19271386b4f1b9d854d4"
  GEMINI_MODEL: "gemini-2.5-flash-lite"
  DATABASE_URL: "mongodb+srv://Astrocare7:Astrocare7337@cluster0.ydviwil.mongodb.net/?appName=Cluster0"
  GOOGLE_CLOUD_PROJECT: "astro-491617"
  GOOGLE_CLOUD_LOCATION: "asia-south1"
  SUPABASE_URL: "https://dmlbtfrdrklwytakzzcd.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbGJ0ZnJkcmtsd3l0YWt6emNkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTIzMTkwOCwiZXhwIjoyMDkwODA3OTA4fQ.GMNyy1vGQmRAd7NmuKcoEuI1SoiAB8iF5Jt51OYt0wk"
  BASE_URL: "https://backend-dot-ai-astrology-481805.as.r.appspot.com"

