# -*- coding: utf-8 -*-

HOUSE_CONFIG = {
    1: {
        "house_number": 1,
        "name": "Ascendant",
        "hindi_name": "Lagna Bhav",
        "is_upachaya": False,
        "natural_ruler": "Mars",
        "natural_sign": "Aries",
        "description": {
            "known_as": "Ascendant (Lagna) in Natural Kundli",
            "lifecycle_stage": "beginning of your life",
            "ruler_reason": "naturally ruled by Mars because our 1st zodiac is Aries and Mars is the ruler of Aries' sign",
            "essence": "House of Self",
            "shows": ["nature", "personality", "physic", "face", "from where native is coming on earth"],
            "personality_rule": "Your 50% Personality comes from Lagna. The planet placed in this house and ruling zodiac sign decide your half Nature, body and Personality."
        },
        "represents": [
            "Self",
            "Nature",
            "Personality",
            "Body Structure",
            "Head",
            "Face",
            "Mind",
            "Pituitary gland",
            "Health",
            "Fitness",
            "Attitude",
            "Behaviour",
            "Self-Branding"
        ]
    },
    2: {
        "house_number": 2,
        "name": "Money House",
        "hindi_name": "Dhan Bhav",
        "is_upachaya": False,
        "natural_ruler": "Venus",
        "natural_sign": "Taurus",
        "description": {
            "known_as": "Money House (Dhan bhav) in Natural Kundli",
            "essence": "house of your Bank balance, Family and Assets",
            "ruler_reason": "naturally ruled by Venus because our 2nd zodiac is Taurus and Venus is the ruler of Taurus sign"
        },
        "represents": [
            "Money",
            "Bank balance",
            "Family",
            "Right Eye",
            "Nose",
            "Voice tone",
            "Food",
            "Banking",
            "Mouth",
            "Family Property",
            "Family Business",
            "Lips",
            "Assets",
            "Jewellery",
            "Gemstone",
            "Insecurity"
        ]
    },
    3: {
        "house_number": 3,
        "name": "Effort House",
        "hindi_name": "Sahaj Bhav",
        "is_upachaya": True,
        "natural_ruler": "Mercury",
        "natural_sign": "Gemini",
        "description": {
            "known_as": "Effort House in Natural Kundli",
            "essence": "house of your efforts, short traveling, Communication and Courage",
            "ruler_reason": "naturally ruled by Mercury because our 3rd zodiac is Gemini and Taurus is the ruler of Gemini sign",
            "nature_type": "Upchaya house",
            "nature_type_behavior": "this house will keep growing according to time and age of native. The significant of this house will continuously increase with time."
        },
        "represents": [
            "Attraction",
            "Change of place",
            "Online",
            "Short Travel",
            "Communication",
            "Media",
            "Internet and Data",
            "Documents",
            "Effort",
            "Marketing",
            "Book",
            "Writing",
            "Ear",
            "Throat",
            "Arms",
            "Hands",
            "Younger Brother",
            "Courage",
            "Bravery",
            "Strength",
            "Networking",
            "Planning",
            "Hobbies",
            "Property Sale"
        ]
    },
    4: {
        "house_number": 4,
        "name": "Comfort House",
        "hindi_name": "Sukh Bhav",
        "is_upachaya": False,
        "natural_ruler": "Moon",
        "natural_sign": "Cancer",
        "description": {
            "known_as": "Comfort House (Sukh bhav) in Natural Kundli",
            "essence": "house of your Mother, Property and Home where person live or born",
            "ruler_reason": "naturally ruled by Moon because our as I told above similarly 4thnd zodiac is Cancer which is ruled by Moon."
        },
        "represents": [
            "House",
            "Land",
            "Property",
            "Homeland",
            "Mother",
            "Comforts",
            "Luxury",
            "Vehicles",
            "Chest",
            "Lungs",
            "Heart",
            "Hotels",
            "Architect",
            "Hospitality",
            "Restaurant",
            "School"
        ]
    },
    5: {
        "house_number": 5,
        "name": "House of Children",
        "hindi_name": "Santan Bhav",
        "is_upachaya": False,
        "natural_ruler": "Sun",
        "natural_sign": "Leo",
        "description": {
            "known_as": "House of Children (Santan Bhav) in Natural Kundli",
            "essence": "house of your Child, Learning and Love",
            "ruler_reason": "naturally ruled by Sun and Leo Zodiac"
        },
        "represents": [
            "Study",
            "Wisdom",
            "Learning",
            "Children",
            "School",
            "Love",
            "Nature",
            "Environment",
            "Affairs",
            "Creativity",
            "Solutions",
            "Execution",
            "Entertainment",
            "Enjoyment",
            "Celebration",
            "Digest",
            "spinal cord",
            "Stomach",
            "Recovery",
            "Romance",
            "Product Development",
            "Artistic Talent"
        ]
    },
    6: {
        "house_number": 6,
        "name": "House of Diseases and Enemy",
        "hindi_name": "Rog and Satru Bhav",
        "is_upachaya": True,
        "natural_ruler": "Mercury",
        "natural_sign": "Virgo",
        "description": {
            "known_as": "House of Diseases and Enemy (Rog and Satru Bhav) in Natural Kundli",
            "essence": "house of your Disease, Loan and Enemy",
            "ruler_reason": "naturally ruled by Mercury and Virgo Zodiac"
        },
        "represents": [
            "Diseases",
            "Enemy",
            "Competition",
            "Service",
            "Conflicts",
            "Loan",
            "Debt",
            "Lawyer",
            "Doctor",
            "Servant",
            "Siblings",
            "Medical",
            "Litigation",
            "Maternal Uncle",
            "Father’s Profession",
            "Kidney",
            "Yoga",
            "Greed",
            "Anger",
            "Lust",
            "Jealousy"
        ]
    },
    7: {
        "house_number": 7,
        "name": "House of Spouse and Marriage",
        "hindi_name": "Vivah bhav",
        "is_upachaya": False,
        "natural_ruler": "Venus",
        "natural_sign": "Libra",
        "description": {
            "known_as": "Seventh house is known as House of Spouse and Marriage (Vivah bhav) in Natural Kundli",
            "essence": "house of opposite gender, Marriage and Spouse",
            "ruler_reason": "naturally ruled by Venus and Libra Zodiac"
        },
        "represents": [
            "Marriage",
            "Spouse",
            "Opposite gender",
            "Daily Interaction",
            "Business",
            "Partner",
            "Trading",
            "Self-Employment",
            "Reproductive organs",
            "Kidney",
            "Urinary bladder",
            "Sex organs",
            "Customers",
            "Retail",
            "Opposition",
            "Meditation"
        ]
    },
    8: {
        "house_number": 8,
        "name": "House of Pain and Obstacles",
        "hindi_name": "Dukh Bhav",
        "is_upachaya": False,
        "natural_ruler": "Mars",
        "natural_sign": "Scorpio",
        "description": {
            "known_as": "Eight house is known as House of Pain and Obstacles (Dukh Bhav) in Natural Kundli",
            "essence": "house of your Pain, Obstacles and Transformation",
            "ruler_reason": "naturally ruled by Mars and Scorpio Zodiac"
        },
        "represents": [
            "Research",
            "Samadhi",
            "Occult",
            "Problem",
            "Depression",
            "Pain",
            "Injury",
            "Surgery",
            "Hurdle",
            "Obstacles",
            "Transformation",
            "Humiliation",
            "Observation",
            "Mystery",
            "Hide",
            "Secret",
            "Mode of Death",
            "Life span",
            "Deep science",
            "Large Intestine",
            "Accidents",
            "Sudden Events",
            "Unearned Money",
            "Astrology",
            "Technology",
            "Manufacture",
            "Bribe",
            "Dowry"
        ]
    },
    9: {
        "house_number": 9,
        "name": "House of Father and Luck",
        "hindi_name": "Gyan Bhav",
        "is_upachaya": False,
        "natural_ruler": "Jupiter",
        "natural_sign": "Sagittarius",
        "description": {
            "known_as": "Nith house is known as House of Father, Luck and Wisdom. (Gyan Bhav) in Natural Kundli",
            "essence": "house of your Father, Guru, Knowledge and God",
            "ruler_reason": "naturally ruled by Jupitar and Sagittarius Zodiac"
        },
        "represents": [
            "Spirituality",
            "Luck",
            "Father",
            "Religion",
            "Religious place",
            "Teachers",
            "Mentors",
            "Higher Learning",
            "Long Travel",
            "Culture",
            "Philosophy",
            "Consultancy",
            "Counselling",
            "Hip joints",
            "Thighs",
            "Idealism",
            "Publication",
            "Colleges"
        ]
    },
    10: {
        "house_number": 10,
        "name": "House of Career and Profession",
        "hindi_name": "Karma Bhav",
        "is_upachaya": True,
        "natural_ruler": "Saturn",
        "natural_sign": "Capricorn",
        "description": {
            "known_as": "Tenth house is known as House of Career and Profession (Karma Bhav)in Natural Kundli",
            "ruler_reason": "naturally ruled by Saturn and Capricorn Zodiac"
        },
        "represents": [
            "Career",
            "Karma",
            "Profession",
            "Public",
            "Knee Joint",
            "Status",
            "Respect",
            "Authority",
            "Government",
            "Administration",
            "Fame"
        ]
    },
    11: {
        "house_number": 11,
        "name": "House of Desire and Income",
        "hindi_name": "Iccha Bhav",
        "is_upachaya": True,
        "natural_ruler": "Saturn",
        "natural_sign": "Aquarius",
        "description": {
            "known_as": "Eleventh house is known as House of Desire and Income (Iccha Bhav) in Natural Horoscope",
            "ruler_reason": "naturally ruled by Saturn and Aquarius Zodiac"
        },
        "represents": [
            "Fulfilment of Desire",
            "Multiplication",
            "Friend circle",
            "Ambition",
            "Gains",
            "Daily Income",
            "Profit",
            "Lower leg",
            "Ankle",
            "Elder Brother",
            "Society",
            "NGOs",
            "Social Works"
        ]
    },
    12: {
        "house_number": 12,
        "name": "House of Detachment and Loss",
        "hindi_name": "Moksha Bhav",
        "is_upachaya": False,
        "natural_ruler": "Jupiter",
        "natural_sign": "Pisces",
        "description": {
            "known_as": "Twelfth house is known as House of Detachment and Loss (Moksha Bhav) in Natural horoscope",
            "ruler_reason": "naturally ruled by Jupitar and Pisces Zodiac"
        },
        "represents": [
            "Bedroom",
            "Moksha",
            "Failure",
            "Disappointment",
            "Loss",
            "Expenses",
            "Hospital",
            "Court",
            "Prison",
            "Isolations",
            "Sex",
            "Pleasure",
            "Luxury Items",
            "Investment",
            "Investor",
            "Foreign travel",
            "Sleep",
            "Detachment",
            "Distraction",
            "Divorce",
            "Feet",
            "Separation",
            "Liberation",
            "Donation"
        ]
    }
}
